export const imdbMovieList = [
    {
        "id": 29043,
        "title": "Schindler&#39;s List",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABX2lS7rcwWAPowMjaselxLlCzI-5oW9UcQRAzfhs6HjHfZCJLdZa9i57rOiSUwacR0V0TZK54CRqiPVZgY_30lthQw.jpg?r=9fb",
        "vtype": "movie",
        "nfid": 60036359,
        "synopsis": "Oskar Schindler becomes an unlikely humanitarian, spending his entire fortune to help save 1,100 Jews from Auschwitz during World War II.",
        "avgrating": 4.3853374,
        "year": 1993,
        "runtime": 11704,
        "imdbid": "tt0108052",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "imdbrating": 8.9,
        "top250": 6,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"BR\":\"Brazil\",\"IN\":\"India\",\"CH\":\"Switzerland\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 30299,
        "title": "Saving Private Ryan",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeduMox1y_Q6IFJ7qqubedROMAOT28H3_apqMSQhvz9hM8ZU5GVcP3FQbJVb_acDSpAYQslYEPfJsbBdu1RVwc394w.jpg?r=ec3",
        "vtype": "movie",
        "nfid": 21878564,
        "synopsis": "Eight U.S. Army Rangers penetrate German-held territory during World War II to find and bring home a soldier whose three brothers have been killed.",
        "avgrating": 4.2588506,
        "year": 1998,
        "runtime": 10184,
        "imdbid": "tt0120815",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
        "imdbrating": 8.6,
        "top250": 26,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"HK\":\"Hong Kong\",\"IL\":\"Israel\",\"JP\":\"Japan\",\"MY\":\"Malaysia\",\"PH\":\"Philippines\",\"SG\":\"Singapore\",\"KR\":\"South Korea\",\"TH\":\"Thailand\",\"TR\":\"Turkey\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 30778,
        "title": "The Pianist",
        "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQPnnhThPWr_u19ajFlcYkYA3CXs7rzNkhZY53-6449ewtY1liJ0XxIUjEf5Gw6c43gpRXAUm00LbKc10WSmSMEBiw.jpg?r=91c",
        "vtype": "movie",
        "nfid": 60025061,
        "synopsis": "Famed Polish pianist Wladyslaw Szpilman struggles to survive the onslaught of Nazi tyranny during World War II in this drama based on his memoirs.",
        "avgrating": 4.077131,
        "year": 2002,
        "runtime": 8938,
        "imdbid": "tt0253474",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "imdbrating": 8.5,
        "top250": 35,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"AU\":\"Australia\",\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 42618,
        "title": "Lawrence of Arabia: Restored Version",
        "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaYsbLFxR6xq2Gnwr-yqcHyIHAwcr5LuK3F8g-MkbHWezuAU_QylI2JmQWzzJ0CzZa5ru6q1_3ZzDdspjnrTLT1JCg.jpg?r=f52",
        "vtype": "movie",
        "nfid": 70012020,
        "synopsis": "This Oscar-winning epic tells the true story of T.E. Lawrence, who helped unite warring Arab tribes to strike back against the Turks in World War I.",
        "avgrating": 4.1902895,
        "year": 1962,
        "runtime": 13624,
        "imdbid": "tt0056172",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
        "imdbrating": 8.3,
        "top250": 111,
        "top250tv": 0,
        "clist": "\"IL\":\"Israel\",\"KR\":\"South Korea\"",
        "titledate": "2015-09-01"
    },
    {
        "id": 67037,
        "title": "1917",
        "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZal9o0hri2EAosoeaRD3clqUYkhnkfK4obodrlhTLVCcNlWC3E7ZFCiAZEZG7k6NALsNhwCSbVYupudJ-3eGsgh1w.jpg?r=8e5",
        "vtype": "movie",
        "nfid": 81140931,
        "synopsis": "During World War I, two British soldiers attempt to cross enemy lines to deliver a message that could save hundreds, including one&#39;s own brother.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 7130,
        "imdbid": "tt8579674",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg",
        "imdbrating": 8.3,
        "top250": 106,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"IT\":\"Italy\",\"MX\":\"Mexico\",\"RO\":\"Romania\",\"more\":\"+3\"",
        "titledate": "2020-11-01"
    },
    {
        "id": 42606,
        "title": "The Bridge on the River Kwai",
        "img": "http://occ-0-1007-1009.1.nflxso.net/art/27797/6ad20fd4ee72c612ecf76bc3a467bc2f79527797.jpg",
        "vtype": "movie",
        "nfid": 60002970,
        "synopsis": "This sweeping epic is set in a World War II Japanese prison camp, where British prisoners are forced to build a bridge as a morale-building exercise.",
        "avgrating": 3.956907,
        "year": 1957,
        "runtime": 9731,
        "imdbid": "tt0050212",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYjE1MzU4NWEtYjhjZS00NzM3LWIyYjQtMWU1M2VkNWYzMzMwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
        "imdbrating": 8.1,
        "top250": 176,
        "top250tv": 0,
        "clist": "\"AU\":\"Australia\",\"IS\":\"Iceland\",\"SE\":\"Sweden\"",
        "titledate": "2015-09-01"
    },
    {
        "id": 53120,
        "title": "Hacksaw Ridge",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfXh286PlqLj3S667WwJK989bjGW9actBkgIxcjj89Jd16LzE7M-JoxurVrySiZCH63-EnmUglAdlit019T3P0kPLw.jpg?r=b3f",
        "vtype": "movie",
        "nfid": 80108975,
        "synopsis": "During World War II, Army medic and conscientious objector Desmond Doss becomes an unlikely hero on an Okinawa battlefield without bearing arms.",
        "avgrating": 0,
        "year": 2016,
        "runtime": 8344,
        "imdbid": "tt2119532",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_SX300.jpg",
        "imdbrating": 8.1,
        "top250": 191,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"CZ\":\"Czech Republic\",\"JP\":\"Japan\",\"KR\":\"South Korea\"",
        "titledate": "2017-05-02"
    },
    {
        "id": 61044,
        "title": "Dances with Wolves",
        "img": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABfywDVurb4JxcksXqo5d87h71idZJetvHxdRzmxnzSpjXkt5KsciTgrK9pzC7j61hKGSahviMn5C32_waGOaW0Zmp09Ugcg.jpg?r=2fb",
        "vtype": "movie",
        "nfid": 60028940,
        "synopsis": "Wounded Civil War soldier John Dunbar tries to commit suicide -- and becomes a hero instead. As a reward, he&#39;s sent to the remote Western frontier.",
        "avgrating": 0,
        "year": 1990,
        "runtime": 10866,
        "imdbid": "tt0099348",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTY3OTI5NDczN15BMl5BanBnXkFtZTcwNDA0NDY3Mw@@._V1_SX300.jpg",
        "imdbrating": 8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"IT\":\"Italy\"",
        "titledate": "2019-02-01"
    },
    {
        "id": 58355,
        "title": "Dunkirk",
        "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTzhpLkmnMjg2wtvWtTtzGuDJNCaeZcCnZSw_vI8p85zm3xH_hKhJ5lXM4ii98-6vtCoymrM5HilcSm2DC7rLIuyRA.jpg?r=85a",
        "vtype": "movie",
        "nfid": 80170278,
        "synopsis": "In May 1940, soldiers and civilians struggle by land, sea and air to evacuate the British army and their allies, Europe&#39;s last hope, from Dunkirk.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 6394,
        "imdbid": "tt5013056",
        "poster": "https://ia.media-imdb.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
        "imdbrating": 7.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"IL\":\"Israel\",\"IT\":\"Italy\",\"LT\":\"Lithuania\",\"KR\":\"South Korea\",\"CH\":\"Switzerland\",\"TR\":\"Turkey\"",
        "titledate": "2018-06-14"
    },
    {
        "id": 26671,
        "title": "The Boy in the Striped Pyjamas",
        "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVZ8XEFzT9ylyLBVzkMZ56XsGgzv9ly-ycoAr5MtkeuhPv-V8f8S_NRa02OyxBwbLu5bXrdxY8lcjyTnuFEJhWtLBw.jpg?r=3bd",
        "vtype": "movie",
        "nfid": 70101375,
        "synopsis": "When his family moves from Berlin to Poland, a young boy befriends a boy who lives on the other side of the fence, unaware he&#39;s a Jewish prisoner.",
        "avgrating": 4.2103167,
        "year": 2008,
        "runtime": 5673,
        "imdbid": "tt0914798",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzMTc3MjA5NF5BMl5BanBnXkFtZTcwOTk3MDE5MQ@@._V1_SX300.jpg",
        "imdbrating": 7.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"PL\":\"Poland\",\"AR\":\"Argentina\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"HK\":\"Hong Kong\",\"HU\":\"Hungary\",\"IL\":\"Israel\",\"MY\":\"Malaysia\",\"more\":\"+7\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 28658,
        "title": "Atonement",
        "img": "https://occ-0-299-1001.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcfCR4Ap0XCSVP9YDisEGHF23A4USyr0FtLmH5fSXRI7XRa9DtSoXOrb4jxw59pEpDv5YeEwRB3EKcDHLtUt1XeHQA.jpg?r=e4c",
        "vtype": "movie",
        "nfid": 70059993,
        "synopsis": "Young Briony fingers a young man for a crime after she discovers a lustful letter and witnesses a sexual encounter between him and her sister.",
        "avgrating": 3.5092578,
        "year": 2007,
        "runtime": 7372,
        "imdbid": "tt0783233",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM0ODc2Mzg1Nl5BMl5BanBnXkFtZTcwMTg4MDU1MQ@@._V1_SX300.jpg",
        "imdbrating": 7.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"AR\":\"Argentina\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"MX\":\"Mexico\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 30925,
        "title": "Glory",
        "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVxie-BIgrAiVBvp7J58F31YA3KEtHmqBTW7ymRwQR-OQG48vxNnHg3oA5H3nxkMXd634N4wmEVtHyygBlh7PYvvtQ.jpg?r=00c",
        "vtype": "movie",
        "nfid": 547335,
        "synopsis": "This stirring drama follows the first African-Americans to serve in combat during the Civil War -- and shows how they helped turn the tide of the war.",
        "avgrating": 3.9812326,
        "year": 1989,
        "runtime": 7332,
        "imdbid": "tt0097441",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQxNDEwZGItZGI1Yy00YjU0LTlkY2YtMGEzODQ0ZjZjMzBhL2ltYWdlXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
        "imdbrating": 7.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"DE\":\"Germany\",\"PL\":\"Poland\",\"BE\":\"Belgium\",\"HK\":\"Hong Kong\",\"MY\":\"Malaysia\",\"PH\":\"Philippines\",\"SG\":\"Singapore\",\"KR\":\"South Korea\",\"TH\":\"Thailand\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 46364,
        "title": "The Wind Rises",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdJrWwm2esfYbBIuAXWM2UOEg7EAEn1hj4Ek4pUXFD1Dfmof6IjWJm-u_mRh_rKHvbEoMvJ8JUym-0-PFpg4jAmzvA.jpg?r=585",
        "vtype": "movie",
        "nfid": 70293674,
        "synopsis": "Animator Hayao Miyazaki spins a decades-spanning tale inspired by the life of Jirô Horikoshi, designer of the World War II fighter plane the Zero.",
        "avgrating": 3.7881186,
        "year": 2013,
        "runtime": 7291,
        "imdbid": "tt2013293",
        "poster": "http://ia.media-imdb.com/images/M/MV5BMTU4NDg0MzkzNV5BMl5BanBnXkFtZTgwODA3Mzc1MDE@._V1_SX300.jpg",
        "imdbrating": 7.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"more\":\"+25\"",
        "titledate": "2016-03-01"
    },
    {
        "id": 26543,
        "title": "A Few Good Men",
        "img": "https://occ-0-2219-1361.1.nflxso.net/art/612eb/0634630a94839e236735c7df1a261b1b867612eb.jpg",
        "vtype": "movie",
        "nfid": 499243,
        "synopsis": "When a cocky military lawyer and his co-counsel are assigned to a murder case, they uncover a hazing ritual that may implicate high-ranking officials.",
        "avgrating": 3.9763427,
        "year": 1992,
        "runtime": 8282,
        "imdbid": "tt0104257",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmRlZDQ1MmUtMzE2Yi00YTkxLTk1MGMtYmIyYWQwODcxYzRlXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg",
        "imdbrating": 7.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"PL\":\"Poland\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"LT\":\"Lithuania\",\"RO\":\"Romania\",\"SK\":\"Slovakia\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 26706,
        "title": "Black Hawk Down",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcvXxk_PbJssaiZbLeZ-E2Aq2r8P2nouZLtZuj-pSkqQNIS_NTBoO4NrYI04x_EkA8lAfKZ4kbf8ZdNhJtnSF5_ZiQ.jpg?r=971",
        "vtype": "movie",
        "nfid": 60022056,
        "synopsis": "When U.S. forces attempt to capture two underlings of a Somali warlord, their helicopters are shot down and the Americans suffer heavy casualties.",
        "avgrating": 3.9871104,
        "year": 2001,
        "runtime": 8676,
        "imdbid": "tt0265086",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWMwMzQxZjQtODM1YS00YmFiLTk1YjQtNzNiYWY1MDE4NTdiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
        "imdbrating": 7.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"BE\":\"Belgium\",\"HK\":\"Hong Kong\",\"MY\":\"Malaysia\",\"PH\":\"Philippines\",\"PT\":\"Portugal\",\"more\":\"+3\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 30173,
        "title": "The Last Samurai",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdUdhmX_Og_BWws7naDMbgSH4UhHFTIRHrjsfmB9DPkB8OkPtAgZEVSmdomX9JV9OQ8zJA0Pz4g_u7mSHnfFtlrovA.jpg?r=919",
        "vtype": "movie",
        "nfid": 60031274,
        "synopsis": "An American hired to instruct the Japanese army in the ways of modern warfare soon learns to respect the samurai that he has been ordered to destroy.",
        "avgrating": 3.8437543,
        "year": 2003,
        "runtime": 9257,
        "imdbid": "tt0325710",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzkyNzQ1Mzc0NV5BMl5BanBnXkFtZTcwODg3MzUzMw@@._V1_SX300.jpg",
        "imdbrating": 7.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"JP\":\"Japan\",\"LT\":\"Lithuania\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 43914,
        "title": "Beasts of No Nation",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABddPVIYN1FVVS0cHJCGvq7diqkdqz1xNf5jxYcsJ-TiRUxPSku_Zn6MVqJ4Irav9TRScpQgw_bwgh9s_N08lIef2ODhXTTgEZ9A07z3k73IvX92ffVwxWaokgPo.jpg?r=ce2",
        "vtype": "movie",
        "nfid": 80044545,
        "synopsis": "When civil war tears his family apart, a young West African boy is forced to join a unit of mercenary fighters and transform into a child soldier.",
        "avgrating": 3.6397514,
        "year": 2015,
        "runtime": 8242,
        "imdbid": "tt1365050",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwMzMzMDI0NF5BMl5BanBnXkFtZTgwNDQ3NjI3NjE@._V1_SX300.jpg",
        "imdbrating": 7.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+27\"",
        "titledate": "2015-10-16"
    },
    {
        "id": 50140,
        "title": "The Last of the Mohicans",
        "img": "http://occ-0-34-32.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcoiNqsgPCbOfiwiMOP7mwmY3LAN1eH4HRGADtKbd-3aw2NS-eutRblDhGaStCyRLDixGaHyVIwSwT0Av6r9L42bUw.jpg?r=5c8",
        "vtype": "movie",
        "nfid": 686619,
        "synopsis": "When rugged frontiersman Hawkeye saves the Munro sisters from a Huron ambush, he ends up in a battle between the British and the French.",
        "avgrating": 3.9588706,
        "year": 1992,
        "runtime": 6714,
        "imdbid": "tt0104691",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU4YzI3ODItYzY3NS00ZTQ2LTg2YzUtNTdjMTVlYjVkYTE4XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
        "imdbrating": 7.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"KR\":\"South Korea\",\"ES\":\"Spain\",\"TR\":\"Turkey\"",
        "titledate": "2016-11-09"
    },
    {
        "id": 27715,
        "title": "The Hurt Locker",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfa_VCrfJhccmCgbpeNu-BDlnK5zUpv9tEvWjwavurO1h1wrPNMw6-EhBhzuNzMNDJZEzdS0mtwlJMuvBp_eDXCOmg.jpg?r=a58",
        "vtype": "movie",
        "nfid": 70105601,
        "synopsis": "Kathryn Bigelow directs this gripping drama following one of the U.S. Army&#39;s elite explosive ordnance disposal teams operating in Iraq.",
        "avgrating": 3.8643427,
        "year": 2008,
        "runtime": 7842,
        "imdbid": "tt0887912",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzEwNzQ1NjczM15BMl5BanBnXkFtZTcwNTk3MTE1Mg@@._V1_SX300.jpg",
        "imdbrating": 7.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"AR\":\"Argentina\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"MX\":\"Mexico\",\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 37757,
        "title": "Enemy at the Gates",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQNIXahwnDKkhhXcBdweSyJhXUV5C8EqzXbCqJPur267Aw3HtQbByenJ1NtqBDVfV_ssLcdckQLY0F7ZXKZqKHaUeg.jpg?r=26d",
        "vtype": "movie",
        "nfid": 60004450,
        "synopsis": "This suspenseful drama follows a battle of wits and wills between renowned Russian sharpshooter Vassili Zaitsev and top German sniper Maj. König.",
        "avgrating": 3.8826222,
        "year": 2001,
        "runtime": 7863,
        "imdbid": "tt0215750",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWFlY2E3ODQtZWNiNi00ZGU4LTkzNWEtZTQ2ZTViMWRhYjIzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
        "imdbrating": 7.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"IT\":\"Italy\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 47642,
        "title": "Fury",
        "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfbaTnJZADAzyC9pJqiC49Y-sScUdy3zjyhIG1n6DobKloO2WFeg6mMbV7TVLlTjPS1JacWYpuZBalZYEymFpZJRXA.jpg?r=efa",
        "vtype": "movie",
        "nfid": 70305907,
        "synopsis": "A green recruit experiences the horror of war with a veteran American tank crew during the vicious combat of World War II&#39;s waning days.",
        "avgrating": 3.794012,
        "year": 2014,
        "runtime": 8097,
        "imdbid": "tt2713180",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4MDU0NTUyN15BMl5BanBnXkFtZTgwMzQxMzY4MjE@._V1_SX300.jpg",
        "imdbrating": 7.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"more\":\"+10\"",
        "titledate": "2016-06-15"
    },
    {
        "id": 27916,
        "title": "Lone Survivor",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXDYCoi8g6bDTBA8hSD0dwkOMH6je1PEicx8faLB12E6VA7kuYBxcOyw6-9vYckD7vWIm2_0DzsFnSYEOw-yqX3lww.jpg?r=22d",
        "vtype": "movie",
        "nfid": 70259795,
        "synopsis": "Mark Wahlberg stars as Navy SEAL Marcus Luttrel in this action-drama based on an ill-fated real-life mission to bring down a Taliban boss.",
        "avgrating": 4.2162704,
        "year": 2013,
        "runtime": 7280,
        "imdbid": "tt1091191",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA0NTgwOTk5Ml5BMl5BanBnXkFtZTcwMjE3NDc5OQ@@._V1_SX300.jpg",
        "imdbrating": 7.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 29302,
        "title": "Zero Dark Thirty",
        "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeOf-bxUpGesnOAC3KzeeUTcj6bPpPgSRNph0nZqXaQ9Gk_gg_wlEG7f9n9mVp2H9lONe2Qvmd7J-tlxaByzs8nVlA.jpg?r=b2c",
        "vtype": "movie",
        "nfid": 70251669,
        "synopsis": "Helmed by Kathryn Bigelow, this gripping dramatization chronicles the 10-year hunt for Osama bin Laden in the wake of the 9/11 terrorist attacks.",
        "avgrating": 3.8190389,
        "year": 2012,
        "runtime": 9383,
        "imdbid": "tt1790885",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4OTUyNzcwN15BMl5BanBnXkFtZTcwMTQ1NDE3OA@@._V1_SX300.jpg",
        "imdbrating": 7.4,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"AR\":\"Argentina\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"MX\":\"Mexico\",\"RO\":\"Romania\",\"ZA\":\"South Africa\",\"KR\":\"South Korea\",\"more\":\"+1\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 34450,
        "title": "Twice Born",
        "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYt3FcazR5Tk7TIOEwOscM2V2pA2guoM25i4KPZhyN10TzRqqnGDUtiwQ48sU76PRn3bn3s7pJfKjpVZw5RmXqkttg.jpg?r=9a6",
        "vtype": "movie",
        "nfid": 70259261,
        "synopsis": "Sixteen years after leaving war-torn Bosnia, a woman returns with her son -- but the visit sparks memories that force her to confront painful truths.",
        "avgrating": 3.731776,
        "year": 2012,
        "runtime": 7762,
        "imdbid": "tt1396226",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwNjUxMjk2NF5BMl5BanBnXkFtZTgwNDYzODE2MDE@._V1_SX300.jpg",
        "imdbrating": 7.4,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 62634,
        "title": "Darkest Hour",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbKONds3-_oB3SIjk3OT-3yJKMBXLehycTeQXewQlQVWUuMw74KvqpPUUnPKn11HEVbM-XwVW4DOoNaEurK0xSx-Pw.jpg?r=3f5",
        "vtype": "movie",
        "nfid": 80189214,
        "synopsis": "As the threat of Nazi invasion looms, newly appointed British Prime Minister Winston Churchill rallies a nation to fight for its very survival.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 7517,
        "imdbid": "tt4555426",
        "poster": "https://m.media-amazon.com/images/M/MV5BNTU4MjMwOTgyMV5BMl5BanBnXkFtZTgwODQzNjY2NDM@._V1_SX300.jpg",
        "imdbrating": 7.4,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"GB\":\"United Kingdom\",\"US\":\"United States\",\"IS\":\"Iceland\",\"PT\":\"Portugal\",\"KR\":\"South Korea\",\"ES\":\"Spain\",\"SE\":\"Sweden\"",
        "titledate": "2019-07-25"
    },
    {
        "id": 26764,
        "title": "The Way Back",
        "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb0PQPi99L2Ftizv3MIS9wjSzH71vhzLzSF1G2d1nZSUaR2IDNPdqJIY4bOZ-5fAypXZp6_kHxeDv-Qw5Rn5z2PJDg.jpg?r=3fa",
        "vtype": "movie",
        "nfid": 70121494,
        "synopsis": "After escaping from a World War II labor camp, a band of soldiers undertake a journey to traverse Siberia, the Gobi Desert and the Himalayas.",
        "avgrating": 3.8946717,
        "year": 2010,
        "runtime": 7990,
        "imdbid": "tt1023114",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5MTc5MTM3Ml5BMl5BanBnXkFtZTcwMDI2NzgwNA@@._V1_SX300.jpg",
        "imdbrating": 7.3,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"BE\":\"Belgium\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 45368,
        "title": "American Sniper",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR9gTNmBeuYPTIlDQ7_8w2Rr8Rpyt8OgQbTCOkKgAyQ7j9q_wGxb0v6YYyxy8NOeRsWGwo3yqZcBFSVYKF5uBsDFtQ.jpg?r=f28",
        "vtype": "movie",
        "nfid": 80013871,
        "synopsis": "U.S. Navy SEAL marksman Chris Kyle racks up an unprecedented number of kills in Iraq, even as his home life starts to slip away from him.",
        "avgrating": 4.1036053,
        "year": 2014,
        "runtime": 7955,
        "imdbid": "tt2179136",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1_SX300.jpg",
        "imdbrating": 7.3,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"DE\":\"Germany\",\"BE\":\"Belgium\",\"GR\":\"Greece\",\"IN\":\"India\",\"IL\":\"Israel\",\"IT\":\"Italy\",\"JP\":\"Japan\",\"ZA\":\"South Africa\",\"KR\":\"South Korea\",\"more\":\"+2\"",
        "titledate": "2015-12-29"
    },
    {
        "id": 49262,
        "title": "13 Hours: The Secret Soldiers of Benghazi",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXY2LsvtSSDb_AXfYcGk2apKKK_KknYjRRvM_Qce1ExyXrLqmEOZY13vdMANttj7_5i4Grvb1jXRJOVY58u5VL64AA.jpg?r=2dd",
        "vtype": "movie",
        "nfid": 80067930,
        "synopsis": "Members of an elite security team battle to save the lives of trapped U.S. Consulate personnel under attack by armed terrorists in Benghazi, Libya.",
        "avgrating": 4.112642,
        "year": 2016,
        "runtime": 8667,
        "imdbid": "tt4172430",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjU3OTQ5NDc3Ml5BMl5BanBnXkFtZTgwOTEwNTkxNzE@._V1_SX300.jpg",
        "imdbrating": 7.3,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"AR\":\"Argentina\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"more\":\"+23\"",
        "titledate": "2016-10-01"
    },
    {
        "id": 63548,
        "title": "The King",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQu_V9I9M5R9i7BeBFvX7TpRDwoS5X61_9lCcayNQnsfERP93pcBuoYEHENwBjn7FcgYUCqlvW5EqbekDdFMqRRQOrYPHH0LxG6_6WQCmOkkE09Vm_NKEz52S2k.jpg?r=259",
        "vtype": "movie",
        "nfid": 80182016,
        "synopsis": "Wayward Prince Hal must turn from carouser to warrior king as he faces hostilities from inside and outside the castle walls in the battle for England.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 8430,
        "imdbid": "tt7984766",
        "poster": "https://m.media-amazon.com/images/M/MV5BOGZhMWFhMTAtNGM3Ni00MTdhLTg3NmMtMDViYTc5ODVkZWVlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        "imdbrating": 7.3,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"more\":\"+19\"",
        "titledate": "2019-11-01"
    },
    {
        "id": 27124,
        "title": "Defiance",
        "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAVuOIw7pQPD5kf7_KZ-pgezwPNPUlpRWEYOszcuDzAh4JJcIJLVqMBAVbOhZ3DJDURgCwjDenkuNCndiSy4X4w9H4g.jpg?r=cbf",
        "vtype": "movie",
        "nfid": 70101696,
        "synopsis": "In this action-packed drama based on an extraordinary true story, four brothers protect more than 1,000 Jewish refugees during World War II.",
        "avgrating": 3.9794872,
        "year": 2008,
        "runtime": 8205,
        "imdbid": "tt1034303",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzODIzMTE3Ml5BMl5BanBnXkFtZTcwNDU1MjQzMg@@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"GB\":\"United Kingdom\",\"BE\":\"Belgium\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"SK\":\"Slovakia\",\"ES\":\"Spain\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 28222,
        "title": "The Patriot",
        "img": "https://occ-0-34-32.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWaM_cr6ktm23niMUAsvJPydcIYCkdc6R-rX471y0IsJzZZoa4rz26s914MYFZocjhWOvRFnfMo_WY_aG58q33FqPg.jpg?r=7df",
        "vtype": "movie",
        "nfid": 60001044,
        "synopsis": "A widower and past war hero just wants to live in peace and farm his land -- until a cruel British officer brings the American Revolution to his door.",
        "avgrating": 3.8400946,
        "year": 2000,
        "runtime": 9901,
        "imdbid": "tt0187393",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzMjE4ODU0MV5BMl5BanBnXkFtZTYwNTI2OTk2._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"NL\":\"Netherlands\",\"BE\":\"Belgium\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"IN\":\"India\",\"IT\":\"Italy\",\"JP\":\"Japan\",\"RO\":\"Romania\",\"SK\":\"Slovakia\",\"more\":\"+2\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 28341,
        "title": "We Were Soldiers",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABT2xbwL-NB1ytYBABsnCAaNyDcNHQAv5ExMYrI2mmYfS2L1u5cTgNTxsIymYcIX9jQ3Px0g64yXkcjVkGkkLPjuAcA.jpg?r=ff8",
        "vtype": "movie",
        "nfid": 60022697,
        "synopsis": "This Vietnam War epic tells the story of the Battle of Ia Drang, which pitted 450 U.S. soldiers against thousands of well-armed Vietnamese troops.",
        "avgrating": 4.044439,
        "year": 2002,
        "runtime": 8312,
        "imdbid": "tt0277434",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDdmN2VmNmYtOGExNC00MmE4LTliOTUtOGMzMzFhMTNlOTM1L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"SE\":\"Sweden\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 28353,
        "title": "Troy",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTIUrYloDdh7-ecrtJPEJMY6ssmc6TjBME9Z5ouyH-SNfP7HlDbxJkzSt7oSnkk-nqX3IzChLQ2ZE0oLEbYNoyHdzw.jpg?r=206",
        "vtype": "movie",
        "nfid": 60034571,
        "synopsis": "The love-struck Prince Paris of Troy kidnaps beauty Helen from her husband, setting the two nations on a collision course for war.",
        "avgrating": 3.7421775,
        "year": 2004,
        "runtime": 9770,
        "imdbid": "tt0332452",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk5MzU1MDMwMF5BMl5BanBnXkFtZTcwNjczODMzMw@@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"DE\":\"Germany\",\"US\":\"United States\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"GR\":\"Greece\",\"IN\":\"India\",\"IL\":\"Israel\",\"IT\":\"Italy\",\"JP\":\"Japan\",\"more\":\"+6\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 45732,
        "title": "&#39;71",
        "img": "https://occ-0-300-2773.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABdG0sDP_1ObimzxjZA8Ll_QsISRI6I2B624GiRrcgZIEGEbGiu8AhGfosp_286Z-YN_hn-mzu8L9TJFXLF62-V-bZw.jpg?r=f1e",
        "vtype": "movie",
        "nfid": 70301585,
        "synopsis": "A young British soldier who&#39;s separated from his unit in Belfast at the height of Northern Ireland&#39;s Troubles must survive a night alone in the city.",
        "avgrating": 3.3290746,
        "year": 2014,
        "runtime": 5959,
        "imdbid": "tt2614684",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1NjE5Njg4M15BMl5BanBnXkFtZTgwMzEyODAzNDE@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"AR\":\"Argentina\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"MX\":\"Mexico\"",
        "titledate": "2016-01-07"
    },
    {
        "id": 48077,
        "title": "Unbroken",
        "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU2fn7KvnbBPJOQbjMRRkHo4ERBpe9rAmcVCr_GWDg0x6Pk0A5_8kJLkGhjMVuF1UZ_sPgTt7iZ6upd1j-FeuydbbQ.jpg?r=493",
        "vtype": "movie",
        "nfid": 70305949,
        "synopsis": "Olympic track star Louis Zamperini becomes a pilot during World War II and endures a brutal struggle for survival when he is captured by the Japanese.",
        "avgrating": 3.835968,
        "year": 2014,
        "runtime": 8242,
        "imdbid": "tt1809398",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3ODg2OTgyOF5BMl5BanBnXkFtZTgwODk1OTAwMzE@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"BR\":\"Brazil\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"HU\":\"Hungary\",\"IN\":\"India\",\"IT\":\"Italy\",\"LT\":\"Lithuania\",\"PT\":\"Portugal\",\"more\":\"+7\"",
        "titledate": "2016-07-20"
    },
    {
        "id": 49570,
        "title": "The Siege of Jadotville",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZMQmLgxh7NEOID3HZQoWA4ZchJ3588jQnYaSuetn1mPKE2px8PffZ6rlmxn6TDQTHrJstSUDeaD54F7xAAtA5fgVxbzIPFvUS2_cM2PaNRFhtXrVN9J5hF6WT8.jpg?r=928",
        "vtype": "movie",
        "nfid": 80041653,
        "synopsis": "Besieged by overwhelming enemy forces, Irish soldiers on a U.N. peacekeeping mission in Africa valiantly defend their outpost in this true story.",
        "avgrating": 3.6982758,
        "year": 2016,
        "runtime": 6506,
        "imdbid": "tt3922798",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZTAxZWViYTUtMDljNi00MmQ5LTk2MzEtYmIwZDNkOTFhZjk0XkEyXkFqcGdeQXVyNjkxOTcwNjc@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+27\"",
        "titledate": "2016-10-07"
    },
    {
        "id": 54960,
        "title": "First They Killed My Father",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfNzMKPPqowgfM3Kd36Y-fWAG1MY1vcfs4lOlDzIhow1sr1h0ZT2-TGCV-uR0iPUt-tTVzTcacO2MrG9ChgwuRLZqT0AFaLmSCq-2ciBjxRx1gekkoxLvc6Mxso.jpg?r=709",
        "vtype": "movie",
        "nfid": 80067522,
        "synopsis": "A 5-year-old girl embarks on a harrowing quest for survival amid the sudden rise and terrifying reign of the Khmer Rouge in Cambodia.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 8208,
        "imdbid": "tt4882376",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzOTQ1NDUwOF5BMl5BanBnXkFtZTgwNjAwNTkwMzI@._V1_SX300.jpg",
        "imdbrating": 7.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+27\"",
        "titledate": "2017-09-15"
    },
    {
        "id": 39793,
        "title": "The Railway Man",
        "img": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABcpFqYPgpPSIUB6_lcgLRh2P0aX9FrefjL23VeGZOARnOdqz5Am0bDOwYzbo7YLsvs7r8UtFtJVFD7GZkYcZoF8Ntw.jpg?r=2f0",
        "vtype": "movie",
        "nfid": 70293617,
        "synopsis": "Decades after World War II, a still-shattered soldier unexpectedly falls in love and sees a bizarre coincidence bring his past back into focus.",
        "avgrating": 3.748189,
        "year": 2013,
        "runtime": 6993,
        "imdbid": "tt2058107",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQzNDU1NjE0NF5BMl5BanBnXkFtZTgwODA3NDczMDE@._V1_SX300.jpg",
        "imdbrating": 7.1,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"US\":\"United States\",\"AU\":\"Australia\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 53420,
        "title": "Arms and the Dudes",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbmHvn_sPbh89YQIpMGp-E60GLbYGipiuTvn80KiO2yKKdJti_xAP5WWQvivL1iIhOZ3Zk_zkxKx3UhL1u5d3lcDSw.jpg?r=8e9",
        "vtype": "movie",
        "nfid": 80080359,
        "synopsis": "Two pals parlay a shaky business plan into a $300 million government contract to supply arms for Afghanistan, then find themselves in way too deep.",
        "avgrating": 0,
        "year": 2016,
        "runtime": 6848,
        "imdbid": "tt2005151",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyNzQ0NzM4MV5BMl5BanBnXkFtZTgwMDI0ODM2OTE@._V1_SX300.jpg",
        "imdbrating": 7.1,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"PL\":\"Poland\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"HK\":\"Hong Kong\",\"HU\":\"Hungary\",\"IT\":\"Italy\",\"LT\":\"Lithuania\",\"MY\":\"Malaysia\",\"PH\":\"Philippines\",\"RO\":\"Romania\",\"more\":\"+5\"",
        "titledate": "2017-05-30"
    },
    {
        "id": 66974,
        "title": "Little Kingdom",
        "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaZXg_S8A7_3bJTsG9db7gELTD2aPBkhgqWSoNMIG2-_EBQNwskVfqOS4fy2ktUvNuDX5aHzNzs8cBBhR27eQLm6AA.jpg?r=861",
        "vtype": "movie",
        "nfid": 81289502,
        "synopsis": "A lovesick soldier deserts his unit during World War II in hopes of reuniting with his wife, only to discover new obstacles to their happiness.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 5927,
        "imdbid": "tt9477066",
        "poster": "https://m.media-amazon.com/images/M/MV5BNTBmOWVhZjEtZDJjOC00ZjQ1LTllMzQtNjBiNTY5YjY5ZjNlXkEyXkFqcGdeQXVyNjkzNDE5MzY@._V1_SX300.jpg",
        "imdbrating": 7.1,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\"",
        "titledate": "2020-10-21"
    },
    {
        "id": 29177,
        "title": "The Last Castle",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVjvDu7Mdl-F9vJ19YxogDxwSt0W6_rsliQaqDlMDji6Ngc_0-t0PxRApmxbnG0l3swAL6VWNXvXDuPU4Jyn33ROng.jpg?r=815",
        "vtype": "movie",
        "nfid": 60021639,
        "synopsis": "Jailed for insubordination, a heroic general is sent to a military prison run by a hard-nosed warden. A battle of wills emerges between the two men.",
        "avgrating": 3.796795,
        "year": 2001,
        "runtime": 7870,
        "imdbid": "tt0272020",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ3MTY0MjU3M15BMl5BanBnXkFtZTYwMzkwOTc5._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"BE\":\"Belgium\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"HU\":\"Hungary\",\"IS\":\"Iceland\",\"IL\":\"Israel\",\"IT\":\"Italy\",\"PT\":\"Portugal\",\"more\":\"+6\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 44153,
        "title": "Charlie Wilson&#39;s War",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABffT0mqv3vMcWARbHx-ZMo6e7p_FhZFaX4bdxUBBOodPAOSr0_6LH0FYYUfzWCoVOAf3Hd7hx7IbcW_j4d1A6tu-bQ.jpg?r=63e",
        "vtype": "movie",
        "nfid": 70060021,
        "synopsis": "A Texas congressman sets a series of events in motion when he conspires with a CIA operative to aid Afghan mujahideen rebels fighting the Soviets.",
        "avgrating": 3.6008177,
        "year": 2007,
        "runtime": 6108,
        "imdbid": "tt0472062",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgwMDgwMDc4MF5BMl5BanBnXkFtZTYwOTU3MDM4._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"PL\":\"Poland\",\"HK\":\"Hong Kong\",\"ZA\":\"South Africa\",\"KR\":\"South Korea\"",
        "titledate": "2015-10-22"
    },
    {
        "id": 44485,
        "title": "The Water Diviner",
        "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaUTxeji_KoKl006XEgN25e4kJpf1i2zf_BLLaF1LjvY3MAzL4IJJgNXpCpl3CRXl9NbAym2FChjmqWWA-cenUmxqA.jpg?r=a4c",
        "vtype": "movie",
        "nfid": 80025390,
        "synopsis": "Years after the presumed death of his three sons in battle, a grieving farmer journeys to Turkey to find them and return them to their homeland.",
        "avgrating": 3.4838002,
        "year": 2014,
        "runtime": 6651,
        "imdbid": "tt3007512",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMzODA4NDYzM15BMl5BanBnXkFtZTgwMTc0Mzc0NDE@._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\"",
        "titledate": "2015-11-01"
    },
    {
        "id": 48753,
        "title": "Suite Francaise",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUBQCKyOGK9hPNTTPU7LY92Zg6JKUEgoaXoPPX_f6BZtddaKb9dmxBJTGHtkGyyaD1q8oQuGBYcLrYLfRtTYTZjqPQ.jpg?r=ad4",
        "vtype": "movie",
        "nfid": 80042309,
        "synopsis": "Waiting for news of her prisoner-of-war husband, a French woman in Nazi-occupied France reluctantly falls for a German officer quartering in her home.",
        "avgrating": 3.366492,
        "year": 2014,
        "runtime": 6444,
        "imdbid": "tt0900387",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMjg3MzQ0NF5BMl5BanBnXkFtZTgwMDYyNzY4NDE@._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"KR\":\"South Korea\"",
        "titledate": "2016-09-04"
    },
    {
        "id": 57180,
        "title": "The Zookeeper&#39;s Wife",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXSQOLyNqEAtlvYY8M-NKbgmOouBaKor7LVTx1K-brWgeySGcXx3IQj9ImE5q1oBaWrr990ZHKLe1TNAhYN7lNizpQ.jpg?r=74f",
        "vtype": "movie",
        "nfid": 80146804,
        "synopsis": "When the Nazis invade Poland, Warsaw Zoo caretakers work with the underground resistance to save Jews from the horrors of the Third Reich.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 7602,
        "imdbid": "tt1730768",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTY3YmZmYmMtZjc3Zi00N2VjLWE5ZGMtN2M0ODkzOGQ5M2UyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTk1MTQ3NDI@._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"US\":\"United States\",\"ES\":\"Spain\"",
        "titledate": "2018-02-24"
    },
    {
        "id": 62357,
        "title": "The Wolf&#39;s Call",
        "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUaspb_LPB8BUl3NTAZZFATzI13SXfq80hl_wnFIMlmXJZF9g0LIJNtdvNyOAplRWyLQyXj3l5ZvS7oPKZsqNSYKEV9X06zkd8uORBLXA2G9VK4oP9QfsSxbhUc.jpg?r=b0d",
        "vtype": "movie",
        "nfid": 81027187,
        "synopsis": "With nuclear war looming, a military expert in underwater acoustics strives to prove things aren&#39;t as they seem -- or sound -- using only his ears.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 6970,
        "imdbid": "tt7458762",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTA5OWMwODctY2ZiMy00MmNmLWFiMWYtM2U2ZjFmYTA2MWQ0XkEyXkFqcGdeQXVyNTc5OTMwOTQ@._V1_SX300.jpg",
        "imdbrating": 7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"MX\":\"Mexico\",\"ZA\":\"South Africa\",\"ES\":\"Spain\",\"more\":\"+1\"",
        "titledate": "2019-06-20"
    },
    {
        "id": 33065,
        "title": "Top Gun",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZtnIneg-BnpRhRicY8fJo1CLzJuLHQdC4nqu_OI4_aZlfdMx68dSNPf_en2d_Vw0G8QpN6FAMO0zwzM-p0RlrDxwA.jpg?r=03b",
        "vtype": "movie",
        "nfid": 1056189,
        "synopsis": "Tom Cruise plays a hotshot pilot who struggles to balance life, responsibility and a love affair while competing at the Navy&#39;s fighter-weapons school.",
        "avgrating": 3.7249575,
        "year": 1986,
        "runtime": 6572,
        "imdbid": "tt0092099",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjQxYTA3ODItNzgxMy00N2Y2LWJlZGMtMTRlM2JkZjI1ZDhhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
        "imdbrating": 6.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"GR\":\"Greece\",\"more\":\"+9\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 34694,
        "title": "Too Young the Hero",
        "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRIdRSr1k14e3mJk0b-j5InZnypkh75yVTLhp7Am5_jxRsb_GkHU9X2ay4h24PThhuRFW5Uhkjasoo84c6tafB-ieQ.jpg?r=2dd",
        "vtype": "movie",
        "nfid": 70206823,
        "synopsis": "Twelve-year-old Calvin manages to join the navy and serves in the battle of Guadalcanal. But when his age is revealed, the boy is sent to the brig.",
        "avgrating": 3.8239737,
        "year": 1988,
        "runtime": 5627,
        "imdbid": "tt0096286",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2MTEzMTY5MF5BMl5BanBnXkFtZTgwMTEwODY0MjE@._V1_SX300.jpg",
        "imdbrating": 6.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"US\":\"United States\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 59170,
        "title": "The Resistance Banker",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABegOOMSfEFC3bw4pl6eSSJCJyfzHT_brGP_xFuJuPN4h3bxsnjaaX8Mjk2gc7uM1LhOqKBBHwxDxIPrJ8s0t2uwB8SFlgg-203fP3fLki7SKiIL_4Hhk7RR91L4.jpg?r=cae",
        "vtype": "movie",
        "nfid": 80244019,
        "synopsis": "Risking his family and future, a banker in occupied Amsterdam slows the Nazi war machine by creating an underground bank to fund the resistance.",
        "avgrating": 0,
        "year": 2018,
        "runtime": 7406,
        "imdbid": "tt4610378",
        "poster": "https://ia.media-imdb.com/images/M/MV5BZGYzYTExOWEtMDlhZi00ZGVkLTg0NWYtZDZlN2UzZWZjYTE4XkEyXkFqcGdeQXVyMjI5NzU3Nzc@._V1_SX300.jpg",
        "imdbrating": 6.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BR\":\"Brazil\",\"more\":\"+26\"",
        "titledate": "2018-09-11"
    },
    {
        "id": 60050,
        "title": "Outlaw King",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfZxuSTNUblSfbo5casoe6pTMgqljsJnu-vIR8CrqRjEqvJny_1IZI2riZftHq996KjhJpQZvxdawczjEJbvBzaq9aocTsASljNF7AbMGLSnbECVvbhKIccA5tw.jpg?r=203",
        "vtype": "movie",
        "nfid": 80190859,
        "synopsis": "In 14th-century Scotland, Robert the Bruce claims the crown and leads a fierce uprising to win back the country&#39;s independence from English rule.",
        "avgrating": 0,
        "year": 2018,
        "runtime": 7298,
        "imdbid": "tt6679794",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2M4YmE2Y2UtNDEwMy00MWQ1LThkNDUtZTc4YWU1ODAyM2Y1XkEyXkFqcGdeQXVyOTIxNTAyMzU@._V1_SX300.jpg",
        "imdbrating": 6.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"more\":\"+24\"",
        "titledate": "2018-11-09"
    },
    {
        "id": 29063,
        "title": "Midway",
        "img": "http://art-2.nflximg.net/c9b1d/441706f29e1dd91ce30462eff92a7a430e2c9b1d.jpg",
        "vtype": "movie",
        "nfid": 60030182,
        "synopsis": "This war drama depicts the U.S. and Japanese forces in the naval Battle of Midway, which became a turning point for Americans during World War II.",
        "avgrating": 3.736084,
        "year": 1976,
        "runtime": 7888,
        "imdbid": "tt0074899",
        "poster": "N/A",
        "imdbrating": 6.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"HK\":\"Hong Kong\",\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 47486,
        "title": "Elizabeth: The Golden Age",
        "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSYvN9BjznkPUCbepz36ohC5opombXFpWG9flRYn_GYi-hZJffawQ0ZsvON35i3CKTUiGMtp7mtPoST-fn7IXdf57w.jpg?r=774",
        "vtype": "movie",
        "nfid": 70045272,
        "synopsis": "Queen Elizabeth steels herself against invasion, treason and betrayal as she pines for the love of swashbuckling adventurer Sir Walter Raleigh.",
        "avgrating": 3.6972365,
        "year": 2007,
        "runtime": 6885,
        "imdbid": "tt0414055",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzODIwNzcyMF5BMl5BanBnXkFtZTcwMTg0MTQ1MQ@@._V1_SX300.jpg",
        "imdbrating": 6.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\"",
        "titledate": "2016-06-01"
    },
    {
        "id": 48578,
        "title": "A Perfect Day",
        "img": "https://occ-0-2506-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABemv6I_ZvmBC4kN2y72rbxw9VLiwyzT3jifdnQXHfD3Csdpuel6Snty4pYDLBF3gFteyP7glZzBFvPTs5fBgM8i_AQ.jpg?r=091",
        "vtype": "movie",
        "nfid": 80058723,
        "synopsis": "During the Yugoslav Wars, three hapless aid workers head out to dislodge a corpse tainting a village&#39;s water. The day goes a bit south from there.",
        "avgrating": 2.8969858,
        "year": 2015,
        "runtime": 6340,
        "imdbid": "tt3577624",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwNjgzOTQ4OV5BMl5BanBnXkFtZTgwMjA5OTM2NTE@._V1_SX300.jpg",
        "imdbrating": 6.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"PL\":\"Poland\",\"RO\":\"Romania\"",
        "titledate": "2016-08-31"
    },
    {
        "id": 67079,
        "title": "The Outpost",
        "img": "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdPEAU1GD2fNgksXjObPUwog0UTlPiRswhYPo101Q5ovaO91StSa8pwcjPcR-OwXFPYmwKQfJvFtZ08TPQ2xuG4K9A.jpg?r=1fb",
        "vtype": "movie",
        "nfid": 81276140,
        "synopsis": "A group of vastly outnumbered U.S. soldiers at a remote Afghanistan base must fend off a brutal offensive by Taliban fighters in the Battle of Kamdesh.",
        "avgrating": 0,
        "year": 2020,
        "runtime": 7387,
        "imdbid": "tt3833480",
        "poster": "https://m.media-amazon.com/images/M/MV5BNWYyMzNjY2EtODVmYi00ODBmLWIyNGMtNDdhMGViY2RhNjcxXkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_SX300.jpg",
        "imdbrating": 6.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"NL\":\"Netherlands\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"IT\":\"Italy\",\"more\":\"+3\"",
        "titledate": "2020-11-03"
    },
    {
        "id": 27615,
        "title": "The Great Raid",
        "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUChfJ7SfbHp6K4fKm8wzD1H2XmfG3A2SXAvUCJGqHxhaZTuZyFNs-RqnKKht96WGX98lv9teK5RIIpU3YZ0VtTofg.jpg?r=e05",
        "vtype": "movie",
        "nfid": 60033312,
        "synopsis": "In World War II, a battalion goes on a daring rescue mission to liberate the Americans and Filipinos who&#39;ve been captured by the Japanese.",
        "avgrating": 3.7384806,
        "year": 2005,
        "runtime": 7964,
        "imdbid": "tt0326905",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExMTEzODI3Nl5BMl5BanBnXkFtZTcwNjA1NzAzMQ@@._V1_SX300.jpg",
        "imdbrating": 6.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"BE\":\"Belgium\",\"CZ\":\"Czech Republic\",\"GR\":\"Greece\",\"HU\":\"Hungary\",\"IN\":\"India\",\"IL\":\"Israel\",\"IT\":\"Italy\",\"more\":\"+2\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 31615,
        "title": "K-19: The Widowmaker",
        "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd07YXhZDpx-rG5KX8qwigfQuBH0Sn0QTKPK4nHkjxQUcw6QHyWnsKEbslYCmjpluqDf724QYzV-3gJhaLtsQbHKSg.jpg?r=4dc",
        "vtype": "movie",
        "nfid": 60023606,
        "synopsis": "On board Russia&#39;s first nuclear ballistic submarine, Capt. Vostrikov must race against time to prevent a Chernobyl-like explosion.",
        "avgrating": 3.6009252,
        "year": 2002,
        "runtime": 8282,
        "imdbid": "tt0267626",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMWY2YjIwNDAtYjQwOC00YjY5LTk2MDUtMjY4ZDdiMjdlNjIzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        "imdbrating": 6.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 65393,
        "title": "Colette",
        "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcc2MhKae19WwTf7D5yjZ7vAfgKaahwRvWcGvL2Yr9oQfgvZ8PRLQ2ULB0YueYk_WGj3PZCA5b8N66U85bZAMyt1Fw.jpg?r=ba0",
        "vtype": "movie",
        "nfid": 81192095,
        "synopsis": "Love offers a pair of captives a sliver of hope as they secretly attempt a dangerous escape from the brutal confinement of Auschwitz.",
        "avgrating": 0,
        "year": 2013,
        "runtime": 7185,
        "imdbid": "tt5437928",
        "poster": "https://m.media-amazon.com/images/M/MV5BZTg5M2MxYzAtZjUwMi00MzRjLTkxNTItZmNjYzUxZjI3YzI3XkEyXkFqcGdeQXVyNDY2MjcyOTQ@._V1_SX300.jpg",
        "imdbrating": 6.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"SK\":\"Slovakia\"",
        "titledate": "2020-05-14"
    },
    {
        "id": 65664,
        "title": "Midway",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXLFbzAcKa63tW9qFBdBsOKOw2LMB21SmlPd4L70KeZoelyFzuQ45O2NqZbeXJp1dMyp3YNLGFlOyhZiW2dRr8LUDw.jpg?r=0ee",
        "vtype": "movie",
        "nfid": 81110665,
        "synopsis": "A gritty United States Navy must face off against an imposing Imperial Japanese Navy in a decisive WWII battle for control of the Pacific.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 8277,
        "imdbid": "tt6924650",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzA5Y2Q2YjktZDYwMi00NTdmLThlMjctMmY5NDgwOWRhZDUxXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        "imdbrating": 6.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"TH\":\"Thailand\"",
        "titledate": "2020-06-14"
    },
    {
        "id": 68120,
        "title": "The Last Full Measure",
        "img": "https://occ-0-2567-2568.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWT7-8XDIRrKjZIejheWbRVVnUpwqiS2_KnDmG6e1RQ29axbX-QlwFemYt6T6Ru-VKRBEJinpjK-45kFGEqeTWm1Aw.jpg?r=8f1",
        "vtype": "movie",
        "nfid": 81118158,
        "synopsis": "A Pentagon lawyer reviews a posthumous petition to award a war hero with the Medal of Honor and discovers the shocking reasons behind its denial.",
        "avgrating": 0,
        "year": 2020,
        "runtime": 6961,
        "imdbid": "tt0783640",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTQyMjBmNDAtNDA0YS00ODFiLTk2OTUtMWM5NzI4NjM1YzhhXkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_SX300.jpg",
        "imdbrating": 6.7,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"SK\":\"Slovakia\"",
        "titledate": "2020-12-27"
    },
    {
        "id": 28158,
        "title": "Tears of the Sun",
        "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbcDrWyi_yjAqnvi-5l8H_q3GIel15OI2q-4oJA1OE_AaYD78MKaxacDt36LTD5AN0NlMst4TRrkHkRLpeygx_QsmQ.jpg?r=435",
        "vtype": "movie",
        "nfid": 60026139,
        "synopsis": "Bruce Willis stars as a Navy SEAL sent to the African jungle to rescue a doctor, only to realize he must also save the refugees in the doctor&#39;s care.",
        "avgrating": 3.789123,
        "year": 2003,
        "runtime": 7263,
        "imdbid": "tt0314353",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmI3YjQ4NjctZTk0Zi00ZDFhLTgyZjAtYWRjZTJjMjMwNjM2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        "imdbrating": 6.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"GB\":\"United Kingdom\",\"AU\":\"Australia\",\"GR\":\"Greece\",\"IL\":\"Israel\",\"ZA\":\"South Africa\",\"TR\":\"Turkey\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 55923,
        "title": "The Ottoman Lieutenant",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc0qBDmuQxuej0S9pCH5GvnCXS0eik0RQBPnRHG3wSYuQ9M7OnZ1P2Ednqob2chVeYqnIe2vI3zeRBdeSuZdFfcdLQ.jpg?r=cb7",
        "vtype": "movie",
        "nfid": 80143796,
        "synopsis": "As World War I looms, an American nurse travels to the Ottoman Empire on a medical mission, where she clashes with a dashing lieutenant.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 6634,
        "imdbid": "tt4943322",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg3ZDVlMjgtNTM4Yi00ZTQ3LThmM2QtYzdjZmRjMTcxMTkzXkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_SX300.jpg",
        "imdbrating": 6.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"US\":\"United States\"",
        "titledate": "2017-12-28"
    },
    {
        "id": 60279,
        "title": "Journey&#39;s End",
        "img": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZVarZlWWAcuYMw_FFxNQ34zh4jvOhwSyLFRxKoALpbx1q6Zw4FJbkY3y8_kdvnmR1rLHF2ryXcjepowyuwXRzoE2A.jpg?r=a3f",
        "vtype": "movie",
        "nfid": 80226711,
        "synopsis": "With a German attack imminent, British soldiers cope with boredom and terror in the trenches of France during the first World War.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 6463,
        "imdbid": "tt3780500",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTAyZDBiYjktMTdlZi00MGQ5LWE5NmItYjI3YWMwN2I0NjYxXkEyXkFqcGdeQXVyNjUzODM0ODI@._V1_SX300.jpg",
        "imdbrating": 6.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"KR\":\"South Korea\"",
        "titledate": "2018-12-01"
    },
    {
        "id": 63415,
        "title": "The Command",
        "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQV9rxELb6S8dbYRihvCTPzpnomXUXYCTAPYKgaaV6ZPQ7JmPrN6KsYb1EdcD3-Q4ysJ6wr8gxdUk31uzkT2-nRmQQ.jpg?r=f89",
        "vtype": "movie",
        "nfid": 81034575,
        "synopsis": "For the crew trapped aboard a sunken Russian submarine the deadliest threat is the bureaucracy on land. Based on a true story.",
        "avgrating": 0,
        "year": 2018,
        "runtime": 7080,
        "imdbid": "tt4951982",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTc4MTIxMWEtMmRhNC00NWEzLWExMWQtMmNiNjA1MDlkZjk3XkEyXkFqcGdeQXVyMTkxODQ4MDg@._V1_SX300.jpg",
        "imdbrating": 6.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"TR\":\"Turkey\"",
        "titledate": "2019-10-19"
    },
    {
        "id": 48271,
        "title": "Hyena Road",
        "img": "https://occ-0-531-2705.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSIgUou66VBp-rHW8v6j8x9_sion9qndUbPYEfDpff1qb_FGNpP3Z4nY7E72fbx_YioU9ds0lQFFZfOPYLZ6YrDT0w.jpg?r=1d0",
        "vtype": "movie",
        "nfid": 80087892,
        "synopsis": "A Canadian sniper, a military officer and a legendary Afghani freedom fighter face the Taliban and walk the fine line between heroism and futility.",
        "avgrating": 3.3056536,
        "year": 2015,
        "runtime": 7215,
        "imdbid": "tt4034452",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzAyMzI2NDMyOV5BMl5BanBnXkFtZTgwMTc2NjIxODE@._V1_SX300.jpg",
        "imdbrating": 6.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"US\":\"United States\"",
        "titledate": "2016-08-02"
    },
    {
        "id": 53896,
        "title": "Against the Sun",
        "img": "https://occ-0-2301-28.1.nflxso.net/art/fc611/d5bf73b0fa446506f08e30f60fefa086af7fc611.jpg",
        "vtype": "movie",
        "nfid": 80026225,
        "synopsis": "During World War II, three U.S. Navy pilots crash-land in the Pacific Ocean, where they fight the elements, hunger and despair in hopes of survival.",
        "avgrating": 0,
        "year": 2014,
        "runtime": 5962,
        "imdbid": "tt2557276",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTk5MjU0NTg3Nl5BMl5BanBnXkFtZTgwNTI3NTUzMzE@._V1_SX300.jpg",
        "imdbrating": 6.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"GB\":\"United Kingdom\"",
        "titledate": "2017-06-30"
    },
    {
        "id": 57688,
        "title": "Geronimo: An American Legend",
        "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWpNdkCxD9XkvybLlGdoEUJwcIHpYdp8JfeF0Spdww1KzRHKEHyh3lSfkt3tMx8UnN1r32YLEFlFkNY2VgOPULNBbQ.jpg?r=d4e",
        "vtype": "movie",
        "nfid": 538871,
        "synopsis": "Wes Studi has the title role in this sprawling Western recounting famed Apache warrior Geronimo&#39;s losing battle with the U.S. Army in the late 1800s.",
        "avgrating": 0,
        "year": 1993,
        "runtime": 6906,
        "imdbid": "tt0107004",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MDY2NjM1OF5BMl5BanBnXkFtZTYwMDE0NzQ5._V1_SX300.jpg",
        "imdbrating": 6.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"DE\":\"Germany\",\"GB\":\"United Kingdom\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"IT\":\"Italy\"",
        "titledate": "2018-04-01"
    },
    {
        "id": 63862,
        "title": "12 Strong",
        "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABe56su6FMtbGQJbl1n3qug4CFGtji-8FZubzNlg2vtbL2BX-HPipyd5mhwNS4DILbVE9yHOmKG61cDi7WhXhrDokfw.jpg?r=f9c",
        "vtype": "movie",
        "nfid": 80196613,
        "synopsis": "Following 9/11, a dozen U.S. soldiers mount up on horseback in Afghanistan to help a local warlord take on a mutual enemy. Inspired by true events.",
        "avgrating": 0,
        "year": 2018,
        "runtime": 7463,
        "imdbid": "tt1413492",
        "poster": "https://m.media-amazon.com/images/M/MV5BNTEzMjk3NzkxMV5BMl5BanBnXkFtZTgwNjY2NDczNDM@._V1_SX300.jpg",
        "imdbrating": 6.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"US\":\"United States\",\"BE\":\"Belgium\",\"IN\":\"India\",\"IT\":\"Italy\",\"JP\":\"Japan\",\"MY\":\"Malaysia\",\"PH\":\"Philippines\",\"SG\":\"Singapore\",\"more\":\"+3\"",
        "titledate": "2019-12-01"
    },
    {
        "id": 65651,
        "title": "Da 5 Bloods",
        "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfRP1VG2t9TLOL6Qo5lVj3IJmm27hkfhSibyZg_tBBPE-wP7qL0Wr-Kpee0_12K9ZrHZVqxUVR8U5I-Crqbw9Dqpw7lfSEMBiiMchpKrXkIGl65Lv9oy-7HOZe0.jpg?r=de7",
        "vtype": "movie",
        "nfid": 81045635,
        "synopsis": "Four African American veterans return to Vietnam decades after the war to find their squad leader&#39;s remains â€” and a stash of buried gold. From Spike Lee.",
        "avgrating": 0,
        "year": 2020,
        "runtime": 9352,
        "imdbid": "tt9777644",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjE4ODEwNzktYjg5Yi00N2YxLWExMmEtMmQyZTBiYWI4MGQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
        "imdbrating": 6.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+27\"",
        "titledate": "2020-06-12"
    },
    {
        "id": 44879,
        "title": "Good Kill",
        "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVzFRmScU7wc4RAQyyXMK7DEWd4TAIY8UAPDouFnbcWQ9ZMgYbRX462eR4a5rInPkkI5AmP5EK7GKJNgXz0tUmMZdA.jpg?r=691",
        "vtype": "movie",
        "nfid": 80015799,
        "synopsis": "As Tommy Egan pilots armed drones over Afghanistan from the safe comfort of Las Vegas, the remote nature of his work begins to raise moral questions.",
        "avgrating": 3.0743144,
        "year": 2014,
        "runtime": 6162,
        "imdbid": "tt3297330",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzNDIxNzE5OF5BMl5BanBnXkFtZTgwODMxMTExNTE@._V1_SX300.jpg",
        "imdbrating": 6.4,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"MY\":\"Malaysia\"",
        "titledate": "2015-12-01"
    },
    {
        "id": 52926,
        "title": "Sand Castle",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABceWR6za2PRk08uX9Y1wH5D1MeOwmCImxCOEHEtVvCRAvgkSEdfe1tV2Zt9l3Fn-U5jlj1t0jlILEP-ZHZ2y8Daj0ORMDs0rW40aQNk2kk3Vqbu06_3B-A0FFqA.jpg?r=b59",
        "vtype": "movie",
        "nfid": 80118916,
        "synopsis": "After the invasion of Iraq in 2003, a reluctant soldier&#39;s platoon is dispatched on a dangerous mission to repair a hostile village&#39;s water system.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 6800,
        "imdbid": "tt2582576",
        "poster": "https://m.media-amazon.com/images/M/MV5BNTQ2YWM1MmItMGVmZi00N2EzLWE4NDUtNTgzODVkNTZlMTBmXkEyXkFqcGdeQXVyMzI3MDEzMzM@._V1_SX300.jpg",
        "imdbrating": 6.3,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"more\":\"+24\"",
        "titledate": "2017-04-21"
    },
    {
        "id": 68874,
        "title": "A Call to Spy",
        "img": "https://occ-0-1430-299.1.nflxso.net/dnm/api/v6/1lcgfy_NA26l7dfd356LqCUdNPM/AAAABbKnB2HEFlBisamPlpx0nLXSBTyccEPk2KPKBJtlwvAeQm-h8E6-S5kr3IO_oxt7HER79zhsET0WXBr4Pfs01hdQa67gJBaJRofNKO_RITI7gAE.jpg?r=d95",
        "vtype": "movie",
        "nfid": 81318865,
        "synopsis": "After France falls to the Nazis, two women seek to support the war effort by spying for a secret agency under Churchill. Based on a true story.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 7466,
        "imdbid": "tt7698468",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTk2ZjJiZTItYTJiOC00YmIyLWI2MmYtZWJkZGMzNDE4NjU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        "imdbrating": 6.3,
        "top250": null,
        "top250tv": null,
        "clist": "\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"BR\":\"Brazil\",\"more\":\"+10\"",
        "titledate": "2021-02-23"
    },
    {
        "id": 57167,
        "title": "Churchill",
        "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYTEM58q2GEqmIDqo1nswiTFL9vp60CuMgrzOjaOSKBY7yHqN1cyYktq9KgUZjEpr9VHoE9fRZJ4t_RBGo7mukMRwg.jpg?r=41a",
        "vtype": "movie",
        "nfid": 80174205,
        "synopsis": "A historical drama about British Prime Minister Winston Churchill&#39;s 96 hours before the D-Day landing in World War II.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 5885,
        "imdbid": "tt2674454",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZGYyN2IyMzctZGNiMi00Y2VmLWFjNGItYTk3NzdkNDAwYTUyXkEyXkFqcGdeQXVyNzY1NzQ2MDk@._V1_SX300.jpg",
        "imdbrating": 6.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"SG\":\"Singapore\"",
        "titledate": "2018-02-22"
    },
    {
        "id": 58319,
        "title": "Billy Lynn&#39;s Long Halftime Walk",
        "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSJMMeTVof_Rg3EWE1HG82IWVJDDpZwPA9zNNdonT6Ts6rrswSQI9jYfrB5Ligx1tN19BwFIr3rFnYMs4pfRt32wIQ.jpg?r=423",
        "vtype": "movie",
        "nfid": 80108597,
        "synopsis": "A soldier whose unit gained acclaim for their fearless actions comes home on leave from Iraq and wrestles with the events that led to his recent fame.",
        "avgrating": 0,
        "year": 2016,
        "runtime": 6796,
        "imdbid": "tt2513074",
        "poster": "https://ia.media-imdb.com/images/M/MV5BMTY1NDI1Nzg4OF5BMl5BanBnXkFtZTgwNjYxOTg4ODE@._V1_SX300.jpg",
        "imdbrating": 6.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"IS\":\"Iceland\",\"KR\":\"South Korea\",\"SE\":\"Sweden\"",
        "titledate": "2018-06-06"
    },
    {
        "id": 53381,
        "title": "War Machine",
        "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRRzXxQSGSpHF1j1u9VkVmkayMoxVbf1KhzvyI5GuO4iMD9xkacmy6Um5MaIaeaVGJGoAvbu1vvlo-zYEG7S8zM2Z7T6lpqkROkDW3HNS_fhsA9roC5Un4IXlDk.jpg?r=3ea",
        "vtype": "movie",
        "nfid": 80068327,
        "synopsis": "When a proud general is tasked with winning an unpopular war, he takes the challenge head-on, not knowing that hubris may be his own worst enemy.",
        "avgrating": 0,
        "year": 2017,
        "runtime": 7358,
        "imdbid": "tt4758646",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcyMzgwNDE1M15BMl5BanBnXkFtZTgwMDAzMDM0MjI@._V1_SX300.jpg",
        "imdbrating": 6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+27\"",
        "titledate": "2017-05-26"
    },
    {
        "id": 65541,
        "title": "The Kill Team",
        "img": "https://occ-0-360-358.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZastR_gI1xPcs7T-hzytTv1DnHTYiWGKlE5X1g6q2S0jhPo6eOYbFLgt8yHzSiNk324APKQcoA-ik6XAXZRe3fRfA.jpg?r=587",
        "vtype": "movie",
        "nfid": 80990339,
        "synopsis": "The conscience of a young soldier in Afghanistan is increasingly disturbed by the bloodthirsty attitude of his platoon&#39;s charismatic new sergeant.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 5250,
        "imdbid": "tt6196936",
        "poster": "https://m.media-amazon.com/images/M/MV5BNTgxNmY2MDAtM2QzYS00MmNmLTk2NWYtNDA1NzRiOGM4MzQwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        "imdbrating": 5.9,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"FR\":\"France\",\"ES\":\"Spain\"",
        "titledate": "2020-06-01"
    },
    {
        "id": 39889,
        "title": "Stalingrad",
        "img": "https://occ-0-299-300.1.nflxso.net/art/5d45a/cc2422133a26e31362da78ab35ae7279a5f5d45a.jpg",
        "vtype": "movie",
        "nfid": 70299617,
        "synopsis": "Amid the horrors of the Battle of Stalingrad in 1942, a group of Russian soldiers holes up in a house occupied by a terrified young woman.",
        "avgrating": 2.9607365,
        "year": 2013,
        "runtime": 7850,
        "imdbid": "tt1966566",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NjE5NTE5MV5BMl5BanBnXkFtZTgwODMxMjMyMTE@._V1_SX300.jpg",
        "imdbrating": 5.6,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"NL\":\"Netherlands\",\"BE\":\"Belgium\",\"IS\":\"Iceland\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 31744,
        "title": "Jarhead 2: Field of Fire",
        "img": "http://occ-1-2218-2219.1.nflxso.net/art/ebeaf/eef8db0a0e1d5af631471484348fae1dd2aebeaf.jpg",
        "vtype": "movie",
        "nfid": 80005495,
        "synopsis": "A Marine contingent stationed in Afghanistan faces a daunting mission when they attempt to help a famously defiant woman escape the Taliban.",
        "avgrating": 3.753083,
        "year": 2014,
        "runtime": 6149,
        "imdbid": "tt3699508",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzUxMTA4Njg0M15BMl5BanBnXkFtZTgwMjcxMDUzMjE@._V1_SX300.jpg",
        "imdbrating": 5.5,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"DE\":\"Germany\",\"AR\":\"Argentina\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"IL\":\"Israel\",\"MX\":\"Mexico\",\"KR\":\"South Korea\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 47576,
        "title": "Jarhead 3: The Siege",
        "img": "http://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABWPOGmp8179KeI5_9vITTl6mlyHvm5Yt3ZCD5ki8-wDoVdvGYp_c9zuTMPah2euYpCDmWhNjlZKnbAoZJMxA0Td8WTOZXLM.jpg?r=d5a",
        "vtype": "movie",
        "nfid": 80091138,
        "synopsis": "When insurgents assault a U.S. embassy, unsuspecting Marines guarding the compound are swept into a ferocious battle to protect civilian lives.",
        "avgrating": 2.80625,
        "year": 2016,
        "runtime": 5337,
        "imdbid": "tt4616014",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2NDYxOTE2OF5BMl5BanBnXkFtZTgwNTQwNTQ4NzE@._V1_SX300.jpg",
        "imdbrating": 5.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"KR\":\"South Korea\"",
        "titledate": "2016-06-07"
    },
    {
        "id": 66362,
        "title": "Gunjan Saxena: The Kargil Girl",
        "img": "https://occ-0-300-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQ5PnV0JBorJCIiin5lQKWHGC_szQJ5zWEwzzAIHXJn0myucPyoIZE9YhpSbhCR-aCO9Ljo5sLz7pBCF7wD7mgY-kv_XfluA0VPNRXs1jrCeC0nDPNJrQXSdt0w.jpg?r=a85",
        "vtype": "movie",
        "nfid": 81292944,
        "synopsis": "Flight Lieutenant Gunjan Saxena makes history in her journey from aspiring aviator to India’s first female combat pilot in the Kargil War.",
        "avgrating": 0,
        "year": 2020,
        "runtime": 6756,
        "imdbid": "tt10350626",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2JmMjczOGEtODg3MS00MGYzLWE5OWYtOTBlNGJmODQyOTE4XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        "imdbrating": 5.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"DE\":\"Germany\",\"NL\":\"Netherlands\",\"PL\":\"Poland\",\"GB\":\"United Kingdom\",\"US\":\"United States\",\"AR\":\"Argentina\",\"AU\":\"Australia\",\"BE\":\"Belgium\",\"more\":\"+22\"",
        "titledate": "2020-08-15"
    },
    {
        "id": 26912,
        "title": "Company of Heroes",
        "img": "https://occ-0-531-2705.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXdrA52kg60_iPGjjT8dPgVVgN9_FZcepHPlon3USZJJObCOwhpF4Eq4_SMMTr0F8_ht70eKrRoVK5WezOvYWON11A.jpg?r=bac",
        "vtype": "movie",
        "nfid": 70266110,
        "synopsis": "During the last major German offensive of World War II, a group of Allied soldiers sets out against all odds to turn the war around.",
        "avgrating": 3.6787214,
        "year": 2013,
        "runtime": 6030,
        "imdbid": "tt2555426",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyMTY1Mjg3NF5BMl5BanBnXkFtZTcwMjc0NTY4OA@@._V1._CR13,16.166671752929688,601,748_SY132_CR8,0,89,132_AL_.jpg_V1_SX300.jpg",
        "imdbrating": 5.1,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CA\":\"Canada\",\"FR\":\"France\",\"NL\":\"Netherlands\",\"GB\":\"United Kingdom\",\"AR\":\"Argentina\",\"BR\":\"Brazil\",\"CO\":\"Colombia\",\"CZ\":\"Czech Republic\",\"HK\":\"Hong Kong\",\"HU\":\"Hungary\",\"more\":\"+13\"",
        "titledate": "2015-04-14"
    },
    {
        "id": 56630,
        "title": "The Last Face",
        "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABX_q0Ud27XBAd4NI3-ZXh2OGnAHJT7rrbcuM1K4Q97Dd5jvYv3BYks9NLsPTgWXAd79y9OCcY4GMRflQF6eruvQRKQ.jpg?r=5ff",
        "vtype": "movie",
        "nfid": 80115030,
        "synopsis": "Savage civil war and a dispute over humanitarian assistance threaten to unravel a checkered romance between an aid director and a doctor.",
        "avgrating": 0,
        "year": 2016,
        "runtime": 7853,
        "imdbid": "tt3286560",
        "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1NTU3OTcyMF5BMl5BanBnXkFtZTgwMDY5Njc3MDI@._V1_SX300.jpg",
        "imdbrating": 4.8,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"RO\":\"Romania\",\"SK\":\"Slovakia\"",
        "titledate": "2017-12-31"
    },
    {
        "id": 70426,
        "title": "Escape and Evasion",
        "img": "https://occ-0-970-2568.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUcX0aE7CRxf9kzEvI0n5GhmCdoY-FrnCDSYsCHr6OKh_ZERrpck5apUdr_8SB6RNIllU4gU2ldhyEqAX7q70Rvs-g.jpg?r=90b",
        "vtype": "movie",
        "nfid": 81435635,
        "synopsis": "A veteran living with PTSD in the wake of a mission gone very wrong must contend with mounting questions about what happened and his own intense guilt.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 5521,
        "imdbid": "tt7423486",
        "poster": "https://m.media-amazon.com/images/M/MV5BMGUwMzhlZTctNTQwMy00NjE2LThiMzQtMDBjOTY1ZmM2ODkwXkEyXkFqcGdeQXVyNTUxNTk4NzA@._V1_SX300.jpg",
        "imdbrating": 4.5,
        "top250": null,
        "top250tv": null,
        "clist": "\"AU\":\"Australia\"",
        "titledate": "2021-04-18"
    },
    {
        "id": 60162,
        "title": "The Bombing",
        "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZJA5ETFrNrbQMILb96G-0ZChkilG4J_XMGLnZj_hw8Ty2_38Ye04Og35W5cwwY9iXJMuWzOZxsJCK1JINm0pOS7cg.jpg?r=57a",
        "vtype": "movie",
        "nfid": 80242252,
        "synopsis": "Amid World War II, a U.S. fighter trains Chinese aviators to help Chongqing defend itself against brutal Japanese air raids.",
        "avgrating": 0,
        "year": 2018,
        "runtime": 5777,
        "imdbid": "tt4743226",
        "poster": "https://m.media-amazon.com/images/M/MV5BNWQ2ZmYzM2EtYTMwZS00YjcxLWEzNGItMGQxM2I2ZDhmN2I2XkEyXkFqcGdeQXVyOTg4MDYyNw@@._V1_SX300.jpg",
        "imdbrating": 3.2,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"IT\":\"Italy\"",
        "titledate": "2018-11-23"
    },
    {
        "id": 52155,
        "title": "The Free State of Jones",
        "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAdRgl5YSOC2ayLVchDWX-jXRoueWOKmluFHZnjJbtndSo7D_zMUex6dTgZwf1Gdi-rwVRjd_Pn8jDkklcIAMUqy0Jw.jpg?r=6d5",
        "vtype": "movie",
        "nfid": 80080158,
        "synopsis": "In this fact-based drama, a rebellious farmer leads a group of Civil War deserters in a fight to establish a mixed-race free state in the deep South.",
        "avgrating": 3.7538614,
        "year": 2016,
        "runtime": 8378,
        "imdbid": "tt1727899",
        "poster": "N/A",
        "imdbrating": 0,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"RO\":\"Romania\",\"ZA\":\"South Africa\"",
        "titledate": "2017-03-13"
    },
    {
        "id": 51745,
        "title": "Eye in the Sky",
        "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdgD_QePT_mhaJdis4qkirlTjY5bmpbcPrB04-kkKHxeK59dxUD7qU64RemKnx8yLHZI__B28GVrTPIcQpUTWG70Zg.jpg?r=6bf",
        "vtype": "movie",
        "nfid": 80080265,
        "synopsis": "While a drone circles over Kenya, politicians and military brass in London clash over a strike that could kill a terrorist -- and an innocent girl.",
        "avgrating": 3.6051435,
        "year": 2015,
        "runtime": 6122,
        "imdbid": "notfound",
        "poster": null,
        "imdbrating": null,
        "top250": 0,
        "top250tv": 0,
        "clist": "\"GB\":\"United Kingdom\",\"CZ\":\"Czech Republic\",\"HU\":\"Hungary\",\"RO\":\"Romania\",\"SK\":\"Slovakia\"",
        "titledate": "2017-02-07"
    },
    {
        "id": 66307,
        "title": "Danger Close: The Battle of Long Tan",
        "img": "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVgXOwCGbbM2tJx8kz7QcmQ97jWz0r3j7fhw5tJHgJXEjqDcCXir_Ih-Hw-C8VO5dXtYqkC-VL6ocqMmbikRoUUnCA.jpg?r=df4",
        "vtype": "movie",
        "nfid": 81207979,
        "synopsis": "Inexperienced troops are thrown into battle in South Vietnam with only the mates beside them and the grit within them to survive. Based on a true story.",
        "avgrating": 0,
        "year": 2019,
        "runtime": 7103,
        "imdbid": null,
        "poster": null,
        "imdbrating": null,
        "top250": null,
        "top250tv": null,
        "clist": "\"AU\":\"Australia\"",
        "titledate": "2020-08-06"
    }
]